// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SyncMessagesExample.Api.StateMachine.Persistence;

#nullable disable

namespace SyncMessagesExample.Api.StateMachine.Persistence.Migrations
{
    [DbContext(typeof(SyncMessagesStateDbContext))]
    partial class SyncMessagesStateDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SyncMessagesExample.Api.StateMachine.SyncMessagesState", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("EndSyncing")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailedReason")
                        .HasColumnType("text");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("MessagesStates")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartSyncing")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CorrelationId");

                    b.ToTable("SyncMessagesState");
                });
#pragma warning restore 612, 618
        }
    }
}
